### ISSUE TITLE
Responsive refactor 

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/lpe-frontend#36]
- [x] make it desktop first 
- [x] add two more breakpoints one for tablet and one for desktop 
- [x] breakpoints number come from `uiConfigs`

```
// desktop

@media (max-width: 1020px){
// tablet
}

@media (max-width: 554px){
// mobie
}

```

**Comment by jinhojang6** [comment]
Updated via https://github.com/acid-info/lpe-frontend/pull/64
