### ISSUE TITLE
block => click => route to the paragraph

### ISSUE THREAD

**Issue by jinhojang6** [acid-info/lpe-frontend#45]
#p-{order}

article => paragraph (textblock)
image => image (imageblocK)

**Comment by jinhojang6** [comment]
https://github.com/acid-info/lpe-frontend/pull/47

**Comment by amirhouieh** [comment]
@jinhojang6 we should try to use Link or A tag as much as possible for accessibility as well as better SEO. Programmatic navigation should only be used if otherwise not possible. 

Please adjust here and anywhere else that it fits.
